import type { Metadata } from 'next';
import './globals.css';
import { WalletProvider } from './context/Index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WalletProvider>
        <body className="bg-slate-100 text-slate-700">{children}</body>
      </WalletProvider>
    </html>
  );
}
